modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "placeonpath"
version = "${version}"
displayName = "PlaceOnPath"
authors = "Maxi"
description = '''
Lets you place any block on grass path blocks without turning them into dirt, and swaps the path for a full-height variant so there is no gap to the block on top.
'''

[[dependencies.placeonpath]]
modId = "forge"
type = "required"
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeonpath]]
modId = "minecraft"
type = "required"
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeonpath]]
modId = "architectury"
type = "required"
versionRange = "[1.32.68,)"
ordering = "AFTER"
side = "BOTH"
