modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "placeonpath"
version = "${version}"
displayName = "PlaceOnPath"
logoFile = "icon.png"
authors = "Maxi"
description = '''
Lets you place any block on dirt path blocks without turning them into dirt, and swaps the path for a full-height variant so there is no gap to the block on top.
'''

[[dependencies.placeonpath]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeonpath]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeonpath]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "placeonpath.mixins.json"
