# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Mod properties
mod_version=1.2.0-26.1-26.1.2
maven_group=de.maxi
archives_name=placeonpath
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
architectury_api_version=20.0.4
fabric_loader_version=0.19.5
fabric_api_version=0.155.3+26.1.2
neoforge_version=26.1.2.109
modmenu_version=18.0.1
neoforge_mod_version=1.2.0-26.1.2
