# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Mod properties
mod_version=1.2.0-26.3
maven_group=de.maxi
archives_name=placeonpath
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.3
# Dependencies
architectury_api_version=22.0.2
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
neoforge_version=26.3.0.16-beta
modmenu_version=21.0.0
neoforge_mod_version=1.2.0-26.3
